server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8&useSSL=false
        username: root
        password: root123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # Druid配置
        druid:
            initial-size: 10  #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
            max-active: 100   #最大连接池数量
            min-idle: 10      #最小连接池数量
            max-wait: 60000   #获取连接时最大等待时间，单位毫秒。
            pool-prepared-statements: true    #是否缓存preparedStatement，也就是PSCache
            max-open-prepared-statements: 100 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL  #验证连接有效性
            test-while-idle: true   #建议配置为true，不影响性能，并且保证安全性。
            test-on-borrow: false   #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            test-on-return: false   #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
            stat-view-servlet:      #内置监控
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true #是否允许一次执行多条语句，缺省关闭

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.arrnos.springlearning.entity
  configuration:
    map-underscore-to-camel-case: true  #使用驼峰法映射属性
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
#    字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
